// Code generated by go generate; DO NOT EDIT.
// This file was generated by handler.go

package handler

// Reset обнуляет все поля структуры
func (st *Handler) Reset() {
	if resetter, ok := interface{}(&st.storage).(interface{ Reset() }); ok {
		resetter.Reset()
	}
	if st.Router != nil {
		if resetter, ok := interface{}(st.Router).(interface{ Reset() }); ok {
			resetter.Reset()
		}
	}
	if st.cfg != nil {
		if resetter, ok := interface{}(st.cfg).(interface{ Reset() }); ok {
			resetter.Reset()
		}
	}
	if st.audit != nil {
		if resetter, ok := interface{}(st.audit).(interface{ Reset() }); ok {
			resetter.Reset()
		}
	}
}
