// Code generated by go generate; DO NOT EDIT.
// This file was generated by message.go

package model

// Reset обнуляет все поля структуры
func (st *Message) Reset() {
	st.IP = ""
	st.Metrics = st.Metrics[:0]
	st.Date = 0
}
