// Code generated by go generate; DO NOT EDIT.
// This file was generated by metric.go

package model

// Reset обнуляет все поля структуры
func (st *Metric) Reset() {
	st.ID = ""
	st.MType = ""
	if st.Delta != nil {
		st.Delta = new(int)
	}
	if st.Value != nil {
		st.Value = new(float64)
	}
	st.Hash = ""
}
