// Package main реализует утилиту формирования метода сброса полей структуры
// к значениям по умолчанию. Утилита анализирует файлы проекта на предмет
// наличия комментария // generate:reset. При нахождении данного комментария
// создается файл с методом Reset для каждой такой структуры.
package main

import (
	"bytes"
	"fmt"
	"go/ast"
	"go/format"
	"go/token"
	"html/template"
	"log/slog"
	"os"
	"path/filepath"
	"slices"
	"strings"

	"golang.org/x/tools/go/packages"
)

// templateReset структура данных для шаблона.
type templateReset struct {
	Package string
	Type    string
	Fields  []Field
}

// Field структура описывает поля передаваемых в шаблон структур.
type Field struct {
	Name string
	Type string
}

// templateStr шаблон для формирования файла с методом сброса полей структуры.
const templateStr = `
// Code generated by go generate; DO NOT EDIT.
// This file was generated by {{toLower .Type}}.go

package {{.Package}}

// Reset обнуляет все поля структуры
func (st *{{.Type}}) Reset() {
{{- range .Fields}}
{{- if eq .Type "string"}}
	st.{{.Name}} = ""
{{- else if or (eq .Type "int") (eq .Type "int64") (eq .Type "uint") (eq .Type "uint64")}}
	st.{{.Name}} = 0
{{- else if eq .Type "bool"}}
	st.{{.Name}} = false
{{- else if or (eq .Type "float32") (eq .Type "float64")}}
	st.{{.Name}} = 0.0
{{- else if contains .Type "[]"}}
	st.{{.Name}} = st.{{.Name}}[:0]
{{- else if contains .Type "map"}}
	clear(st.{{.Name}})
{{- else if and (contains .Type "*") (isPrimitive .Type)}}
	if st.{{.Name}} != nil {
		st.{{.Name}} = new({{baseType .Type}})
	}
{{- else if and (contains .Type "*") (not (isPrimitive .Type))}}
	if st.{{.Name}} != nil {
		if resetter, ok := interface{}(st.{{.Name}}).(interface{ Reset() }); ok {
			resetter.Reset()
		} 
	}
{{- else if not (isPrimitive .Type)}}
	if resetter, ok := interface{}(&st.{{.Name}}).(interface{ Reset() }); ok {
		resetter.Reset()
	}
{{- else}}
	st.{{.Name}} = {{.Type}}{}
{{- end}}
{{- end}}
}
`

// funcMap прокидывем функции в шаблон.
var funcMap = template.FuncMap{
	"toLower":  strings.ToLower,
	"contains": strings.Contains,
	"baseType": func(s string) string {
		return strings.TrimPrefix(s, "*")
	},
	"isPrimitive": func(s string) bool {
		s = strings.TrimPrefix(s, "*")
		return slices.Contains([]string{"int", "int64", "uint", "uint64", "bool", "float32", "float64", "string"}, s)
	},
}

var tmpl = template.Must(
	template.New("reset").
		Funcs(funcMap).
		Parse(templateStr))

func main() {
	// Конфигурация загрузки
	cfg := &packages.Config{
		Mode: packages.NeedSyntax | packages.NeedName | packages.NeedTypesInfo,
		Dir:  ".",
	}

	// Загружаем все пакеты рекурсивно
	pkgs, err := packages.Load(cfg, "../../internal/...")
	if err != nil {
		slog.Error("Ошибка загрузки пакетов:", slog.Any("error", err))
		return
	}

	// Перебираем все пакеты и файлы
	for _, pkg := range pkgs {
		for _, file := range pkg.Syntax {
			fName := pkg.Fset.File(file.Pos()).Name()

			// Перебираем объявления напрямую
			for _, decl := range file.Decls {
				genDecl, ok := decl.(*ast.GenDecl)
				if !ok || genDecl.Tok != token.TYPE {
					continue
				}

				// Проверяем каждый тип в объявлении
				for _, spec := range genDecl.Specs {
					typeSpec, ok := spec.(*ast.TypeSpec)
					if !ok {
						continue
					}

					if hasResetComment(genDecl.Doc) {
						if structType, ok := typeSpec.Type.(*ast.StructType); ok {
							fields := make([]Field, 0, len(structType.Fields.List))
							for _, field := range structType.Fields.List {
								names := field.Names

								for _, name := range names {
									fields = append(fields, Field{Name: name.Name, Type: exprToString(field.Type)})
								}
							}

							if err := generateFile(file, fName, typeSpec.Name.Name, fields); err != nil {
								slog.Error("Ошибка генерации файла:", slog.Any("error", err))
								return
							}
						}
					}
				}
			}
		}
	}
}

// hasResetComment проверяет наличие комментария "// generate:reset"
func hasResetComment(doc *ast.CommentGroup) bool {
	if doc == nil {
		return false
	}

	for _, comment := range doc.List {
		if strings.Contains(comment.Text, "generate:reset") {
			return true
		}
	}

	return false
}

// generateFile генерируем файл по шаблону
func generateFile(file *ast.File, fName, tName string, fields []Field) error {
	// генерируем код по шаблону
	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, templateReset{Package: file.Name.Name, Type: tName, Fields: fields}); err != nil {
		return err
	}

	// форматируем код
	bufFmt, err := format.Source(buf.Bytes())
	if err != nil {
		return err
	}

	// записываем сгенерированный код в файл
	basename := strings.TrimSuffix(fName, filepath.Ext(fName))
	err = os.WriteFile(fmt.Sprintf("%s.reset.go", basename), bufFmt, 0644)
	if err != nil {
		return err
	}

	return nil
}

// exprToString преобразует тип в строковое представление.
func exprToString(expr ast.Expr) string {
	switch t := expr.(type) {
	case *ast.Ident:
		return t.Name

	case *ast.SelectorExpr:
		// time.Time
		return fmt.Sprintf("%s.%s", exprToString(t.X), t.Sel.Name)

	case *ast.ArrayType:
		// Слайс
		return fmt.Sprintf("[]%s", exprToString(t.Elt))

	case *ast.StarExpr:
		// Указатель
		return fmt.Sprintf("*%s", exprToString(t.X))

	case *ast.MapType:
		// Карта
		return "map"

	case *ast.InterfaceType:
		// Интерфейс
		return "interface{}"

	default:
		return fmt.Sprintf("<%T>", expr)
	}
}
